package pl.sda.programming.introduction.model;

import java.time.LocalDate;
import java.util.Objects;

/**
 * The employee
 * @author kamil.jasek@gmail.com
 */
public class Employee extends Object {

    public static final int MIN_SALARY = 1000;

    // class fields - immutable fields
    private final String firstName;
    private final String lastName;
    private final String pesel;
    private final LocalDate birthday;

    // class fields - mutable
    private String jobTitle;
    private float salary = MIN_SALARY;

    public Employee(String firstName, String lastName, String pesel, LocalDate birthday) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.pesel = pesel;
        this.birthday = birthday;
    }

    // better would be to return float or boolean
    // instead of println
    public void setSalary(float amount) {
        if (amount >= MIN_SALARY) {
            salary = amount;
        } else {
            System.out.println("Salary not modified!!! Current salary is " + salary);
        }
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getPesel() {
        return pesel;
    }

    public LocalDate getBirthday() {
        return birthday;
    }

    public String getJobTitle() {
        return jobTitle;
    }

    public float getSalary() {
        return salary;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public String getFullName() {
        return firstName + " " + lastName;
    }

//    @Override
//    public String toString() {
//        return "firstName=" + firstName + ", lastname=" + lastName + ", salary=" + salary;
//    }

    // generated by IDE
    @Override
    public String toString() {
        return "Employee{" +
                "firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", pesel='" + pesel + '\'' +
                ", birthday=" + birthday +
                ", jobTitle='" + jobTitle + '\'' +
                ", salary=" + salary +
                '}';
    }

//    @Override
//    public boolean equals(Object obj) {
//        if (this == obj) {
//            return true;
//        }
//        if (obj instanceof Employee) {
//            Employee emp = (Employee) obj;
//            if (firstName == null || !firstName.equals(emp.firstName)) {
//                return false;
//            }
//            if (lastName == null || !lastName.equals(emp.lastName)) {
//                return false;
//            }
//            if (birthday == null || !birthday.equals(emp.birthday)) {
//                return false;
//            }
//            return true;
//        }
//        return false;
//    }

    // generate equals

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Employee employee = (Employee) o;
        return Float.compare(employee.salary, salary) == 0 &&
                Objects.equals(firstName, employee.firstName) &&
                Objects.equals(lastName, employee.lastName) &&
                Objects.equals(pesel, employee.pesel) &&
                Objects.equals(birthday, employee.birthday) &&
                Objects.equals(jobTitle, employee.jobTitle);
    }

    @Override
    public int hashCode() {
        return Objects.hash(firstName, lastName, pesel, birthday, jobTitle, salary);
    }
}
